export const ESTILOS = {
  pagina: {
    minHeight: '100vh',
    background: 'var(--gray-50, #f8fafc)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '40px 16px',
  },
  contenedor: {
    width: '100%',
    maxWidth: '560px',
  },
  encabezado: {
    marginBottom: '32px',
  },
  badge: {
    display: 'inline-block',
    fontSize: '0.75rem',
    fontWeight: '700',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--primary-700, #1d4ed8)',
    background: 'var(--primary-50, #eff6ff)',
    borderRadius: '999px',
    padding: '4px 12px',
    marginBottom: '12px',
  },
  titulo: {
    fontSize: '1.6rem',
    fontWeight: '800',
    color: 'var(--gray-900, #0f172a)',
    margin: '0 0 8px',
  },
  subtitulo: {
    fontSize: '0.9rem',
    color: 'var(--gray-500, #64748b)',
    margin: 0,
  },
  tarjeta: {
    background: '#fff',
    borderRadius: 'var(--radius-lg, 12px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.05)',
    padding: '32px',
    marginBottom: '24px',
  },
  campo: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    fontSize: '0.82rem',
    fontWeight: '600',
    color: 'var(--gray-700, #334155)',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    border: '1.5px solid var(--gray-200, #e2e8f0)',
    borderRadius: 'var(--radius-md, 8px)',
    fontSize: '0.9rem',
    color: 'var(--gray-800, #1e293b)',
    outline: 'none',
    transition: 'border-color 0.15s',
    boxSizing: 'border-box',
  },
  inputFocus: {
    border: '1.5px solid var(--primary-500, #3b82f6)',
  },
  inputError: {
    border: '1.5px solid var(--error, #ef4444)',
  },
  inputReadonly: {
    background: 'var(--gray-50, #f8fafc)',
    color: 'var(--gray-500, #64748b)',
    cursor: 'not-allowed',
    fontFamily: 'monospace',
    letterSpacing: '0.08em',
  },
  select: {
    width: '100%',
    padding: '10px 14px',
    border: '1.5px solid var(--gray-200, #e2e8f0)',
    borderRadius: 'var(--radius-md, 8px)',
    fontSize: '0.9rem',
    color: 'var(--gray-800, #1e293b)',
    outline: 'none',
    background: '#fff',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
    boxSizing: 'border-box',
    appearance: 'none',
  },
  fila: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  btnPrincipal: {
    width: '100%',
    padding: '13px 0',
    background: 'var(--primary-600, #2563eb)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-md, 8px)',
    fontSize: '0.95rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  panelExito: {
    background: '#fff',
    borderRadius: 'var(--radius-lg, 12px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.05)',
    overflow: 'hidden',
  },
  encabezadoExito: {
    background: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
    padding: '24px 32px',
    color: '#fff',
  },
  tituloExito: {
    fontSize: '1.1rem',
    fontWeight: '700',
    margin: '0 0 4px',
  },
  subtituloExito: {
    fontSize: '0.85rem',
    opacity: 0.85,
    margin: 0,
  },
  cuerpoExito: {
    padding: '28px 32px',
  },
  credencial: {
    background: 'var(--gray-50, #f8fafc)',
    borderRadius: 'var(--radius-md, 8px)',
    border: '1px solid var(--gray-200, #e2e8f0)',
    padding: '16px 20px',
    marginBottom: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  credencialLabel: {
    fontSize: '0.75rem',
    fontWeight: '700',
    color: 'var(--gray-500, #64748b)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  credencialValor: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: 'var(--gray-900, #0f172a)',
    fontFamily: 'monospace',
    letterSpacing: '0.08em',
  },
  advertenciaPIN: {
    background: '#fefce8',
    border: '1px solid #fde047',
    borderRadius: 'var(--radius-md, 8px)',
    padding: '12px 16px',
    fontSize: '0.82rem',
    color: '#854d0e',
    marginBottom: '12px',
  },
  enlaceBox: {
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 'var(--radius-md, 8px)',
    padding: '14px 16px',
    marginBottom: '20px',
  },
  enlaceLabel: {
    fontSize: '0.75rem',
    fontWeight: '700',
    color: '#15803d',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '6px',
  },
  enlaceTexto: {
    fontSize: '0.82rem',
    color: '#166534',
    wordBreak: 'break-all',
    fontFamily: 'monospace',
  },
  enlaceNota: {
    fontSize: '0.8rem',
    color: '#166534',
    marginTop: '8px',
    marginBottom: '12px',
    lineHeight: '1.4',
  },
  btnCopiar: {
    marginTop: '8px',
    padding: '6px 14px',
    background: '#dcfce7',
    color: '#15803d',
    border: '1px solid #86efac',
    borderRadius: 'var(--radius-sm, 6px)',
    fontSize: '0.8rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  btnNuevo: {
    width: '100%',
    padding: '11px 0',
    background: 'transparent',
    color: 'var(--primary-600, #2563eb)',
    border: '1.5px solid var(--primary-200, #bfdbfe)',
    borderRadius: 'var(--radius-md, 8px)',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '8px',
  },
  navTabs: {
    display:       'flex',
    gap:           '4px',
    background:    'var(--gray-100, #f1f5f9)',
    borderRadius:  'var(--radius-md, 8px)',
    padding:       '4px',
    marginBottom:  '24px',
  },
  tab: (activo) => ({
    flex:         1,
    padding:      '8px 0',
    background:   activo ? '#fff' : 'transparent',
    color:        activo ? 'var(--gray-900, #0f172a)' : 'var(--gray-500, #64748b)',
    border:       'none',
    borderRadius: 'var(--radius-sm, 6px)',
    fontSize:     '0.85rem',
    fontWeight:   activo ? '700' : '500',
    cursor:       'pointer',
    boxShadow:    activo ? '0 1px 3px rgba(0,0,0,0.08)' : 'none',
    transition:   'all 0.15s',
    textDecoration: 'none',
    textAlign: 'center'
  }),
  errorGlobal: {
    background: '#fef2f2',
    border: '1px solid #fca5a5',
    borderRadius: 'var(--radius-md, 8px)',
    padding: '12px 16px',
    fontSize: '0.85rem',
    color: '#991b1b',
    marginBottom: '16px',
  },
  errorCampo: {
    fontSize: '0.78rem',
    color: 'var(--error, #ef4444)',
    marginTop: '4px',
    display: 'block',
  },
  confirmacionTexto: {
    fontSize: '0.9rem',
    color: 'var(--gray-600, #475569)',
    margin: '0 0 16px',
    lineHeight: 1.5,
  },
  resumenConfirmacion: {
    border: '1px solid var(--gray-200, #e2e8f0)',
    borderRadius: 'var(--radius-md, 8px)',
    overflow: 'hidden',
    marginBottom: '20px',
  },
  itemResumen: {
    display: 'grid',
    gridTemplateColumns: '130px 1fr',
    gap: '12px',
    padding: '10px 12px',
    borderBottom: '1px solid var(--gray-100, #f1f5f9)',
    fontSize: '0.84rem',
  },
  itemResumenFinal: {
    borderBottom: 'none',
  },
  itemResumenCorreo: {
    background: '#eff6ff',
  },
  resumenLabel: {
    color: 'var(--gray-500, #64748b)',
    fontWeight: '700',
  },
  resumenValor: {
    color: 'var(--gray-900, #0f172a)',
    fontWeight: '600',
    overflowWrap: 'anywhere',
  },
  avisoConfirmacion: {
    background: '#fefce8',
    border: '1px solid #fde047',
    borderRadius: 'var(--radius-md, 8px)',
    padding: '10px 12px',
    fontSize: '0.82rem',
    color: '#854d0e',
    marginBottom: '20px',
    lineHeight: 1.4,
  },
};
