FROM node:22-bookworm-slim

WORKDIR /app

# Copiar todo el monorepo para que NPM Workspaces detecte los package.json
COPY . .

# Instalar dependencias para poblar los volúmenes anónimos en desarrollo
RUN npm install
