"""Add actualizado_por to AlertaInconsistencia

Revision ID: 89e354c5dc13
Revises: bfed2103863b
Create Date: 2026-07-15 20:34:08.162297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e354c5dc13'
down_revision: Union[str, Sequence[str], None] = 'bfed2103863b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario_alertas_inconsistencia', sa.Column('actualizado_por', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario_alertas_inconsistencia', 'actualizado_por')
    # ### end Alembic commands ###
