"""Add ultimo_envio_correo

Revision ID: 8acd71dbe4ae
Revises: 89e354c5dc13
Create Date: 2026-07-15 21:10:37.117564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acd71dbe4ae'
down_revision: Union[str, Sequence[str], None] = '89e354c5dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesos_manuales', sa.Column('ultimo_envio_correo', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accesos_manuales', 'ultimo_envio_correo')
    # ### end Alembic commands ###
