"""Add sagrilaft_reporte_id

Revision ID: 94d838962205
Revises: 8acd71dbe4ae
Create Date: 2026-07-16 05:30:35.897587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d838962205'
down_revision: Union[str, Sequence[str], None] = '8acd71dbe4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formularios', sa.Column('sagrilaft_reporte_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formularios', 'sagrilaft_reporte_id')
    # ### end Alembic commands ###
