"""Add formulario_alertas_inconsistencia table

Revision ID: bfed2103863b
Revises: e8ec39b5b93f
Create Date: 2026-07-15 18:23:02.683601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfed2103863b'
down_revision: Union[str, Sequence[str], None] = 'e8ec39b5b93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario_alertas_inconsistencia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('formulario_id', sa.String(), nullable=False),
    sa.Column('tipo_campo', sa.String(), nullable=False),
    sa.Column('nombre_documento', sa.String(), nullable=False),
    sa.Column('valor_formulario', sa.Text(), nullable=True),
    sa.Column('valor_documento', sa.Text(), nullable=True),
    sa.Column('seccion_referencia', sa.String(), nullable=True),
    sa.Column('estado_auditoria', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_formulario_alertas_inconsistencia_formulario_id', 'formulario_alertas_inconsistencia', ['formulario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_formulario_alertas_inconsistencia_formulario_id', table_name='formulario_alertas_inconsistencia')
    op.drop_table('formulario_alertas_inconsistencia')
    # ### end Alembic commands ###
