"""add_moneda_declaracion_otra

Revision ID: d62426367da1
Revises: e67dacb63e47
Create Date: 2026-07-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62426367da1'
down_revision: Union[str, Sequence[str], None] = 'e67dacb63e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'formularios',
        sa.Column(
            'moneda_declaracion_otra',
            sa.String(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formularios', 'moneda_declaracion_otra')
    # ### end Alembic commands ###
