"""permitir_nulos_en_campos_booleanos

Revision ID: e8ec39b5b93f
Revises: f2a3b4c5d6e7
Create Date: 2026-07-14 17:19:16.676192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ec39b5b93f'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formulario_clasificacion_tributaria', 'autorretenedor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'gran_contribuyente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'entidad_sin_animo_lucro',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'retencion_ica',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'impuesto_ica',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'entidad_oficial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formulario_clasificacion_tributaria', 'exento_retencion_fuente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    op.alter_column('formularios', 'realiza_operaciones_moneda_extranjera',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formularios', 'realiza_operaciones_moneda_extranjera',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'exento_retencion_fuente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'entidad_oficial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'impuesto_ica',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'retencion_ica',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'entidad_sin_animo_lucro',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'gran_contribuyente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('formulario_clasificacion_tributaria', 'autorretenedor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
