"""
Puertos de repositorio — contratos que los adaptadores de persistencia deben cumplir.

Cada protocolo describe las operaciones de BD que un servicio de aplicación necesita,
sin mencionar SQLAlchemy, ORM ni ningún detalle de infraestructura.

Los tipos de retorno usan `Any` como placeholder hasta que la Fase 5 introduzca
entidades de dominio completas (con todos los campos) que reemplacen los ORM models.

SOLID:
- I (Segregación de Interfaces): un protocolo por servicio; cada uno expone solo
  lo que su consumidor necesita.
- D (Inversión de Dependencias): los servicios dependen de estos protocolos,
  no de SQLAlchemy ni de implementaciones concretas.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class RepositorioFormulario(Protocol):
    """Puerto de persistencia para FormularioService."""

    def obtener_por_id(self, formulario_id: str) -> Optional[Any]: ...
    def obtener_por_codigo(self, codigo: str) -> Optional[Any]: ...
    def agregar(self, formulario: Any) -> None: ...
    def confirmar(self) -> None: ...
    def refrescar(self, obj: Any) -> None: ...


@runtime_checkable
class RepositorioDocumento(Protocol):
    """Puerto de persistencia para DocumentoService."""

    def buscar(self, formulario_id: str, doc_id: str) -> Optional[Any]: ...
    def listar_activos(self, formulario_id: str) -> List[Any]: ...
    def agregar(self, documento: Any) -> None: ...
    def confirmar(self) -> None: ...
    def refrescar(self, obj: Any) -> None: ...


@runtime_checkable
class RepositorioValidacion(Protocol):
    """Puerto de persistencia para ValidacionService."""

    def obtener_formulario(self, formulario_id: str) -> Optional[Any]: ...
    def limpiar_validaciones(self, formulario_id: str) -> None: ...
    def agregar_validacion(self, resultado: Any) -> None: ...
    def confirmar(self) -> None: ...
    def refrescar(self, obj: Any) -> None: ...


@runtime_checkable
class RepositorioExpediente(Protocol):
    """Puerto de persistencia para ExpedienteService."""

    def listar(
        self,
        estados: List[Any],
        tipo_contraparte: Optional[str] = None,
        busqueda: Optional[str] = None,
    ) -> List[Any]: ...

    def obtener(self, formulario_id: str, estados: List[Any]) -> Optional[Any]: ...

    def buscar_documento_descargable(
        self, formulario_id: str, doc_id: str, estados: List[Any]
    ) -> Optional[Any]: ...

    def listar_documentos(self, formulario_id: str) -> List[Any]: ...

    def contar_documentos(self, ids_formularios: List[str]) -> Dict[str, int]: ...

    def confirmar(self) -> None: ...


@runtime_checkable
class RepositorioFirma(Protocol):
    """Puerto de persistencia para FirmaService."""

    def obtener_formulario(self, formulario_id: str) -> Optional[Any]: ...
    def obtener_formulario_por_zoho_id(self, request_id: str) -> Optional[Any]: ...
    def obtener_pdf(self, formulario_id: str) -> Optional[Any]: ...
    def obtener_acceso_manual(self, formulario_id: str) -> Optional[Any]: ...
    def obtener_certificado(self, formulario_id: str) -> Optional[Any]: ...
    def agregar_documento(self, documento: Any) -> None: ...
    def confirmar(self) -> None: ...


@runtime_checkable
class RepositorioAccesoManual(Protocol):
    """Puerto de persistencia para AccesoManualService."""

    def obtener_acceso_por_token(self, token: str) -> Optional[Any]: ...
    def obtener_acceso_por_formulario_id(
        self, formulario_id: str, *, cargar_formulario: bool = False
    ) -> Optional[Any]: ...
    def obtener_formulario_por_codigo(self, codigo_peticion: str) -> Optional[Any]: ...
    def obtener_acceso_por_formulario(self, formulario: Any) -> Optional[Any]: ...
    def listar_accesos(self) -> List[Any]: ...
    def agregar_formulario(self, formulario: Any) -> None: ...
    def agregar_acceso(self, acceso: Any) -> None: ...
    def flush(self) -> None: ...
    def confirmar(self) -> None: ...
    def refrescar(self, obj: Any) -> None: ...
